# Generated by Django 5.2.8 on 2026-03-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video_ads/%Y/%m/%d')),
                ('video_url', models.URLField(blank=True, help_text='Use this if you want to link an external video instead of uploading one.', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
