# Generated by Django 5.2.8 on 2026-03-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_videoad'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_author',
            field=models.BooleanField(default=False, help_text='Can write news drafts from author dashboard'),
        ),
    ]
